image: node:lts-alpine

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  stage: deploy
  script:
    - apk add --no-cache openjdk11
    artifacts:
      paths:
        - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

# test:
#   stage: test
#   script:
#     - apk add --no-cache openjdk11
#     - npm install
#     -
#   artifacts:
#     paths:
#       - test
#   rules:
#     - if: '$CI_COMMIT_BRANCH != "main"'
